In [19]:
import numpy as np
import cv2

face_cascade = cv2.CascadeClassifier('d:/opencv/sources/data/haarcascades/haarcascade_frontalface_default.xml')
# lena.png
fileName = 'd:/opencv/images/loreal.jpg'
image = cv2.imread(fileName, cv2.COLOR_BGR2GRAY) #cv2.IMREAD_COLOR)
np_image = np.copy(image)
gray_image = cv2.cvtColor(np_image, cv2.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(gray_image)
print(type(faces))
print(faces)
print(faces.shape)
print('number of faces detected :' + str(faces[0]))
print('image shape ' + str(image.shape))
print('image shape[0] ' + str(image.shape[0]))
for (x,y,w,h) in faces:
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),1)
cv2.rectangle(image, ((0,image.shape[0] -25)),(270, image.shape[0]), (0,255,255), -1)
cv2.putText(image, "Number of faces detected: " + str(faces.shape[0]), (0,image.shape[0] -500), cv2.FONT_HERSHEY_TRIPLEX, .75, (0,255,0), 1)
cv2.imshow('original face', image)
#cv2.imshow('grey face', gray_image) 
#cv2.imshow('result ', faces)
cv2.waitKey(0)
cv2.destroyAllWindows()


<class 'numpy.ndarray'>
[[1667  514   27   27]
 [ 886  123   31   31]
 [ 412  126   37   37]
 [ 992  139   38   38]
 [1560  275   32   32]
 [1364    9   61   61]
 [ 808  129   65   65]
 [ 866  133   53   53]
 [ 928  131   64   64]
 [ 573    5   65   65]
 [ 515  253   65   65]
 [1561  685   61   61]
 [1208   15   54   54]
 [ 623  109  101  101]
 [1770   29   62   62]
 [ 524  295   50   50]
 [ 544   77   58   58]
 [1626   65   61   61]
 [ 433   71   60   60]
 [  90   74   72   72]
 [ 642  442   81   81]
 [ 660  152   63   63]
 [1189  150   59   59]
 [ 919   71   74   74]
 [1032  160   68   68]
 [1363   32   64   64]
 [1304   98   57   57]
 [1438   86   68   68]
 [ 581  162   56   56]
 [1802   97   64   64]
 [1585  624   67   67]
 [ 656  105   45   45]
 [ 715   99   52   52]
 [1569  478  100  100]]
(34, 4)
number of faces detected :[1667  514   27   27]
image shape (900, 1920, 3)
image shape[0] 900
